tasks:
    - name: build and run docker container and generate TLS certs
      init: docker build -t jq-pilot .
      before: sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./nginx/ssl/private/nginx-selfsigned.key -out ./nginx/ssl/certs/nginx-selfsigned.crt -subj "/C=PE/ST=Lima/L=Lima/O=Acme Inc. /OU=IT Department/CN=acme.com" && sudo openssl dhparam -out ./nginx/ssl/dhparam.pem 4096
      command: docker run -v /etc/ssl:/etc/ssl -p 8000:8000 jq-pilot

ports:
    - port: 8000
      onOpen: open-preview
      name: instructions
