version: "3.7"

services:
    backend:
        container_name: backend
        build:
            context: .
        networks:
            - jq-pilot
        ports:
            - 8000:8000
        restart: unless-stopped

    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 8081:443
            - 8080:80
        networks:
            - jq-pilot
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/snippets:/etc/nginx/snippets
            # generate all the below yourself if running this locally, gitpod is already
            # set up to generate them on startup
            - ./nginx/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./nginx/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./nginx/ssl/dhparam.pem:/etc/nginx/dhparam.pem
        restart: unless-stopped

networks:
    jq-pilot:
        driver: bridge
