# fly.toml app configuration file generated for jq-pilot on 2023-04-29T20:39:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jq-pilot"
primary_region = "lhr"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
