#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jq-pilot"
primary_region = "lhr"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
